name: virteng-env
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - fenics-dolfinx=0.9
  - ipython=8.10.0
  - ipywidgets=8.0.4
  - widgetsnbextension=4.0.5
  - jupyterlab_widgets=3.0.5
  - joblib
  - jupyter=1.0.0
  - jupytext
  - matplotlib
  - pandas
  - pandoc
  - pytest
  - pyyaml
  - scikit-learn
  - scipy
  - xlrd
  - pip
  - pip:
    - -e .
 
